[package]
name = "multip"
version = "0.0.0"
authors = ["Esa-Matti Suuronen <esa-matti@suuronen.org>"]
edition = "2021"

[dependencies]
nix = { version = "0.28.0", features = ["signal"] }
libc = "0.2"
memchr = "2.7.2"
lazy_static = "1.4.0"
regex = "1.3.3"
